import json

with open("new_jobs_data.json", "r", encoding="utf-8") as f:
    jobs = json.load(f)

more_jobs = [
    {
        "id": "busfahrer",
        "title": "Busfahrer",
        "aliases": ["Linienbusfahrer", "Reisebusfahrer"],
        "category": "Logistik & Verkehr",
        "kldbCode": "52132",
        "officialKldbLabel": "Fachkraft - Personenverkehr",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 36800, "p25Year": 31500, "p75Year": 42500, "minYear": 26000, "maxYear": 52000,
        "trendPercent": 3.8, "typicalEducation": "Ausbildung / Umschulung",
        "shortDesc": "Sichere Beförderung von Fahrgästen im Linien- und Reiseverkehr."
    },
    {
        "id": "polizist",
        "title": "Polizist",
        "aliases": ["Polizeibeamter", "Kriminalbeamter"],
        "category": "Verwaltung & öffentlicher Bereich",
        "kldbCode": "73212",
        "officialKldbLabel": "Fachkraft - Polizei",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "B", # often Besoldung
        "medianYear": 52500, "p25Year": 45000, "p75Year": 62000, "minYear": 35000, "maxYear": 80000,
        "trendPercent": 2.5, "typicalEducation": "Ausbildung bei der Polizei",
        "shortDesc": "Gewährleistung der öffentlichen Sicherheit und Ordnung sowie Strafverfolgung."
    },
    {
        "id": "feuerwehrmann",
        "title": "Feuerwehrmann",
        "aliases": ["Brandmeister", "Feuerwehrfrau"],
        "category": "Verwaltung & öffentlicher Bereich",
        "kldbCode": "54112",
        "officialKldbLabel": "Fachkraft - Feuerwehr und Brandschutz",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "B", # often Besoldung
        "medianYear": 48200, "p25Year": 41000, "p75Year": 55500, "minYear": 34000, "maxYear": 70000,
        "trendPercent": 2.2, "typicalEducation": "Ausbildung zum Brandmeister",
        "shortDesc": "Rettung von Menschen und Tieren, Brandbekämpfung und technische Hilfeleistung."
    },
    {
        "id": "verwaltungswirt",
        "title": "Verwaltungswirt",
        "aliases": ["Diplom-Verwaltungswirt", "Beamter im gehobenen Dienst"],
        "category": "Verwaltung & öffentlicher Bereich",
        "kldbCode": "73113",
        "officialKldbLabel": "Spezialist - Öffentliche Verwaltung",
        "requirementLevel": 3,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "B",
        "medianYear": 58500, "p25Year": 49000, "p75Year": 70000, "minYear": 40000, "maxYear": 85000,
        "trendPercent": 2.0, "typicalEducation": "Duales Studium (Öffentliche Verwaltung)",
        "shortDesc": "Sachbearbeitung und Führungsaufgaben im gehobenen nichttechnischen Verwaltungsdienst."
    },
    {
        "id": "kfz-mechatroniker",
        "title": "Kfz-Mechatroniker",
        "aliases": ["Automechaniker", "Kfz-Mechaniker"],
        "category": "Handwerk & Bau",
        "kldbCode": "25212",
        "officialKldbLabel": "Fachkraft - Kraftfahrzeugtechnik",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 37200, "p25Year": 31000, "p75Year": 45000, "minYear": 26000, "maxYear": 55000,
        "trendPercent": 3.0, "typicalEducation": "Duale Ausbildung",
        "shortDesc": "Wartung, Reparatur und Fehlerdiagnose an Kraftfahrzeugen und deren Systemen."
    },
    {
        "id": "maschinen-und-anlagenfuehrer",
        "title": "Maschinen- und Anlagenführer",
        "aliases": ["Anlagenführer"],
        "category": "Industrie & Technik",
        "kldbCode": "25102",
        "officialKldbLabel": "Fachkraft - Maschinenbau und Betriebstechnik",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 41500, "p25Year": 34500, "p75Year": 49000, "minYear": 29000, "maxYear": 60000,
        "trendPercent": 2.5, "typicalEducation": "Duale Ausbildung",
        "shortDesc": "Einrichten, Bedienen und Umrüsten von industriellen Fertigungsmaschinen."
    },
    {
        "id": "verfahrensmechaniker",
        "title": "Verfahrensmechaniker",
        "aliases": ["Verfahrensmechaniker für Kunststoff- und Kautschuktechnik"],
        "category": "Industrie & Technik",
        "kldbCode": "21312",
        "officialKldbLabel": "Fachkraft - Kunststoff- und Kautschukherstellung",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 42800, "p25Year": 36000, "p75Year": 51000, "minYear": 30000, "maxYear": 62000,
        "trendPercent": 2.5, "typicalEducation": "Duale Ausbildung",
        "shortDesc": "Einrichten und Bedienen von Produktionsanlagen zur Herstellung von Kunststoffteilen."
    },
    {
        "id": "logistikmanager",
        "title": "Logistikmanager",
        "aliases": ["Logistikleiter", "Supply Chain Manager"],
        "category": "Logistik & Verkehr",
        "kldbCode": "51314",
        "officialKldbLabel": "Experte - Lagerwirtschaft",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 65500, "p25Year": 52000, "p75Year": 85000, "minYear": 40000, "maxYear": 120000,
        "trendPercent": 3.0, "typicalEducation": "Studium Logistik / BWL",
        "shortDesc": "Steuerung und Optimierung von unternehmensinternen und -übergreifenden Logistikprozessen."
    },
    {
        "id": "lagerarbeiter",
        "title": "Lagerhelfer",
        "aliases": ["Lagerarbeiter", "Lagerist (Helfer)"],
        "category": "Logistik & Verkehr",
        "kldbCode": "51311",
        "officialKldbLabel": "Helfer - Lagerwirtschaft",
        "requirementLevel": 1,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 31200, "p25Year": 26000, "p75Year": 37500, "minYear": 22000, "maxYear": 45000,
        "trendPercent": 3.5, "typicalEducation": "Anlernberuf",
        "shortDesc": "Verladen, Transportieren und Sortieren von Waren im Lagerbetrieb."
    },
    {
        "id": "reinigungskraft",
        "title": "Reinigungskraft",
        "aliases": ["Gebäudereiniger", "Raumpfleger"],
        "category": "Verwaltung & öffentlicher Bereich", # Not the best category, maybe Handwerk
        "kldbCode": "54211",
        "officialKldbLabel": "Helfer - Objekt-, Werte- und Personenschutz",
        "requirementLevel": 1,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 28500, "p25Year": 24000, "p75Year": 33500, "minYear": 20000, "maxYear": 40000,
        "trendPercent": 4.5, "typicalEducation": "Anlernberuf",
        "shortDesc": "Reinigung und Pflege von Büros, öffentlichen Gebäuden und Verkehrsmitteln."
    },
    {
        "id": "sachbearbeiter",
        "title": "Sachbearbeiter",
        "aliases": ["Kaufmännischer Sachbearbeiter", "Büroangestellter"],
        "category": "Kaufmännische Berufe",
        "kldbCode": "71402",
        "officialKldbLabel": "Fachkraft - Büro- und Sekretariat",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 40500, "p25Year": 33000, "p75Year": 49000, "minYear": 28000, "maxYear": 60000,
        "trendPercent": 2.2, "typicalEducation": "Kaufmännische Ausbildung",
        "shortDesc": "Eigenständige Bearbeitung spezifischer Fachaufgaben in der Verwaltung von Unternehmen."
    },
    {
        "id": "recruiter",
        "title": "Recruiter",
        "aliases": ["Talent Acquisition Specialist", "Personalbeschaffer"],
        "category": "Kaufmännische Berufe",
        "kldbCode": "71513",
        "officialKldbLabel": "Spezialist - Personalvermittlung",
        "requirementLevel": 3,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 51500, "p25Year": 41500, "p75Year": 63000, "minYear": 32000, "maxYear": 80000,
        "trendPercent": 3.8, "typicalEducation": "Studium oder kaufm. Ausbildung",
        "shortDesc": "Identifikation, Ansprache und Auswahl geeigneter Kandidaten für offene Stellen."
    },
    {
        "id": "steuerberater",
        "title": "Steuerberater",
        "aliases": ["Tax Consultant", "Tax Manager"],
        "category": "Finanzen, Recht & Controlling",
        "kldbCode": "71634",
        "officialKldbLabel": "Experte - Steuerberatung",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "C", # BBG censored
        "medianYear": 82000, "p25Year": 62000, "p75Year": 115000, "minYear": 50000, "maxYear": 180000,
        "trendPercent": 2.8, "typicalEducation": "Steuerberaterexamen",
        "shortDesc": "Steuerliche und betriebswirtschaftliche Beratung von Unternehmen und Privatpersonen."
    },
    {
        "id": "unternehmensberater",
        "title": "Unternehmensberater",
        "aliases": ["Management Consultant", "Consultant"],
        "category": "Finanzen, Recht & Controlling",
        "kldbCode": "71304",
        "officialKldbLabel": "Experte - Unternehmensorganisation und -strategie",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 78000, "p25Year": 60000, "p75Year": 105000, "minYear": 50000, "maxYear": 160000,
        "trendPercent": 3.5, "typicalEducation": "Wirtschaftsstudium (Master)",
        "shortDesc": "Analyse und Optimierung von Geschäftsprozessen, Strategien und Organisationsstrukturen."
    },
    {
        "id": "finanzberater",
        "title": "Finanzberater",
        "aliases": ["Vermögensberater", "Financial Advisor"],
        "category": "Finanzen, Recht & Controlling",
        "kldbCode": "72113",
        "officialKldbLabel": "Spezialist - Bankwesen",
        "requirementLevel": 3,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 62500, "p25Year": 48000, "p75Year": 85000, "minYear": 35000, "maxYear": 130000,
        "trendPercent": 2.0, "typicalEducation": "Ausbildung Bankkaufmann + Weiterbildung",
        "shortDesc": "Individuelle Beratung von Kunden in Fragen der Geldanlage, Finanzierung und Altersvorsorge."
    },
    {
        "id": "hotelmanager",
        "title": "Hotelmanager",
        "aliases": ["Hoteldirektor", "General Manager Hotel"],
        "category": "Gastronomie & Hotellerie",
        "kldbCode": "63314",
        "officialKldbLabel": "Experte - Hotelservice",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 58500, "p25Year": 45000, "p75Year": 82000, "minYear": 35000, "maxYear": 120000,
        "trendPercent": 2.5, "typicalEducation": "Studium Tourismusmanagement",
        "shortDesc": "Betriebswirtschaftliche Führung und strategische Ausrichtung eines Hotelbetriebs."
    },
    {
        "id": "kuechenchef",
        "title": "Küchenchef",
        "aliases": ["Head Chef", "Chefkoch"],
        "category": "Gastronomie & Hotellerie",
        "kldbCode": "63223",
        "officialKldbLabel": "Spezialist - Speisenzubereitung",
        "requirementLevel": 3,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 45000, "p25Year": 36000, "p75Year": 56000, "minYear": 30000, "maxYear": 85000,
        "trendPercent": 3.5, "typicalEducation": "Ausbildung Koch + Meister",
        "shortDesc": "Leitung der gesamten Küchenorganisation, Personalplanung und Speisekartengestaltung."
    },
    {
        "id": "bauleiter",
        "title": "Bauleiter",
        "aliases": ["Bauleiter im Hochbau", "Construction Manager"],
        "category": "Bau & Immobilien",
        "kldbCode": "31114",
        "officialKldbLabel": "Experte - Hochbau",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 68500, "p25Year": 55000, "p75Year": 86000, "minYear": 45000, "maxYear": 120000,
        "trendPercent": 3.0, "typicalEducation": "Studium Bauingenieurwesen",
        "shortDesc": "Koordination, technische Überwachung und kaufmännische Abwicklung von Bauprojekten auf der Baustelle."
    },
    {
        "id": "vermessungstechniker",
        "title": "Vermessungstechniker",
        "aliases": ["Geomatiker"],
        "category": "Bau & Immobilien",
        "kldbCode": "31212",
        "officialKldbLabel": "Fachkraft - Vermessungstechnik",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 41500, "p25Year": 34500, "p75Year": 50000, "minYear": 28000, "maxYear": 62000,
        "trendPercent": 2.2, "typicalEducation": "Duale Ausbildung",
        "shortDesc": "Durchführung von Lage- und Höhenmessungen im Gelände sowie Auswertung von Geodaten."
    },
    {
        "id": "facility-manager",
        "title": "Facility Manager",
        "aliases": ["Objektleiter", "Gebäudemanager"],
        "category": "Bau & Immobilien",
        "kldbCode": "31113",
        "officialKldbLabel": "Spezialist - Facility Management",
        "requirementLevel": 3,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 54200, "p25Year": 44000, "p75Year": 68000, "minYear": 35000, "maxYear": 90000,
        "trendPercent": 3.5, "typicalEducation": "Studium Facility Management",
        "shortDesc": "Strategische und operative Bewirtschaftung von Gebäuden, Anlagen und Einrichtungen."
    },
    {
        "id": "produktionsingenieur",
        "title": "Produktionsingenieur",
        "aliases": ["Fertigungsingenieur", "Manufacturing Engineer"],
        "category": "Ingenieurwesen & Technik",
        "kldbCode": "27114",
        "officialKldbLabel": "Experte - Produktionstechnik",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 71500, "p25Year": 58000, "p75Year": 88000, "minYear": 48000, "maxYear": 120000,
        "trendPercent": 3.0, "typicalEducation": "Studium Maschinenbau/Produktionstechnik",
        "shortDesc": "Planung, Optimierung und technische Betreuung von industriellen Fertigungsprozessen."
    },
    {
        "id": "verfahrenstechniker",
        "title": "Verfahrenstechniker",
        "aliases": ["Prozessingenieur", "Chemical Engineer"],
        "category": "Ingenieurwesen & Technik",
        "kldbCode": "27214",
        "officialKldbLabel": "Experte - Verfahrenstechnik",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 74500, "p25Year": 60000, "p75Year": 92000, "minYear": 50000, "maxYear": 130000,
        "trendPercent": 2.8, "typicalEducation": "Studium Verfahrenstechnik",
        "shortDesc": "Entwicklung und Skalierung chemischer, physikalischer oder biologischer Produktionsprozesse."
    },
    {
        "id": "cnc-fachkraft",
        "title": "CNC-Fachkraft",
        "aliases": ["CNC-Programmierer", "Zerspanungsmechaniker CNC"],
        "category": "Industrie & Technik",
        "kldbCode": "24232",
        "officialKldbLabel": "Fachkraft - Zerspanungstechnik",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 45800, "p25Year": 38500, "p75Year": 54000, "minYear": 32000, "maxYear": 68000,
        "trendPercent": 2.5, "typicalEducation": "Weiterbildung zur CNC-Fachkraft",
        "shortDesc": "Programmierung, Rüstung und Bedienung von computergesteuerten Werkzeugmaschinen."
    },
    {
        "id": "werkzeugmechaniker",
        "title": "Werkzeugmechaniker",
        "aliases": ["Werkzeugmacher"],
        "category": "Industrie & Technik",
        "kldbCode": "24222",
        "officialKldbLabel": "Fachkraft - Werkzeugtechnik",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 46500, "p25Year": 39500, "p75Year": 55500, "minYear": 33000, "maxYear": 70000,
        "trendPercent": 2.0, "typicalEducation": "Duale Ausbildung",
        "shortDesc": "Anfertigung und Instandhaltung von hochpräzisen Stanz-, Umform- und Spritzgusswerkzeugen."
    },
    {
        "id": "heilerziehungspfleger",
        "title": "Heilerziehungspfleger",
        "aliases": ["HEP", "Heilpädagoge"],
        "category": "Bildung & Soziales",
        "kldbCode": "83112",
        "officialKldbLabel": "Fachkraft - Erziehung",
        "requirementLevel": 2,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 44500, "p25Year": 38000, "p75Year": 52000, "minYear": 32000, "maxYear": 62000,
        "trendPercent": 3.8, "typicalEducation": "Ausbildung an Fachschulen",
        "shortDesc": "Pädagogische und pflegerische Unterstützung von Menschen mit körperlicher oder geistiger Behinderung."
    },
    {
        "id": "kommissionierer",
        "title": "Kommissionierer",
        "aliases": ["Picker", "Lagerhelfer (Kommissionierung)"],
        "category": "Logistik & Verkehr",
        "kldbCode": "51311",
        "officialKldbLabel": "Helfer - Lagerwirtschaft",
        "requirementLevel": 1,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "A",
        "medianYear": 31500, "p25Year": 26500, "p75Year": 38000, "minYear": 22000, "maxYear": 46000,
        "trendPercent": 3.5, "typicalEducation": "Anlernberuf",
        "shortDesc": "Zusammenstellung von Waren und Gütern aus einem Lagerbestand anhand von Auftragslisten."
    },
    {
        "id": "berufsschullehrer",
        "title": "Berufsschullehrer",
        "aliases": ["Lehrer (Berufsschule)", "Studienrat (berufliche Schulen)"],
        "category": "Bildung & Soziales",
        "kldbCode": "84154",
        "officialKldbLabel": "Experte - Lehrkräfte berufliche Schulen",
        "requirementLevel": 4,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "B", # Often Beamte
        "medianYear": 75500, "p25Year": 64000, "p75Year": 88000, "minYear": 52000, "maxYear": 108000,
        "trendPercent": 2.5, "typicalEducation": "Lehramtsstudium & Referendariat",
        "shortDesc": "Fachunterricht und pädagogische Begleitung von Auszubildenden an berufsbildenden Schulen."
    },
    {
        "id": "immobilienmakler",
        "title": "Immobilienmakler",
        "aliases": ["Real Estate Agent", "Makler"],
        "category": "Bau & Immobilien",
        "kldbCode": "71413",
        "officialKldbLabel": "Spezialist - Immobilienwirtschaft",
        "requirementLevel": 3,
        "salaryReferencePeriod": "2023",
        "salarySource": "BA Entgeltatlas",
        "salarySourceType": "Amtliche Statistik",
        "dataCategory": "C", # Highly variable/provision-based
        "medianYear": 52000, "p25Year": 38000, "p75Year": 75000, "minYear": 25000, "maxYear": 150000,
        "trendPercent": 1.5, "typicalEducation": "Kaufmännische Ausbildung / Maklererlaubnis",
        "shortDesc": "Vermittlung von Immobilienkäufen, -verkäufen und -vermietungen auf Provisionsbasis."
    }
]

jobs.extend(more_jobs)

with open("new_jobs_data.json", "w", encoding="utf-8") as f:
    json.dump(jobs, f, ensure_ascii=False, indent=2)

print(f"Total jobs: {len(jobs)}")
